/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ReportCreateDto,
  ReportDto,
  ReportUpdateDto,
  ReportsDto
} from '.././model';

import { axiosInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create a price report
 */
export const createReport = (
    reportCreateDto: ReportCreateDto,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ReportDto>(
      {url: `/reports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reportCreateDto, signal
    },
      options);
    }
  


export const getCreateReportMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{data: ReportCreateDto}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{data: ReportCreateDto}, TContext> => {

const mutationKey = ['createReport'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReport>>, {data: ReportCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  createReport(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReportMutationResult = NonNullable<Awaited<ReturnType<typeof createReport>>>
    export type CreateReportMutationBody = ReportCreateDto
    export type CreateReportMutationError = unknown

    /**
 * @summary Create a price report
 */
export const useCreateReport = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{data: ReportCreateDto}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReport>>,
        TError,
        {data: ReportCreateDto},
        TContext
      > => {

      const mutationOptions = getCreateReportMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Admin list of reports
 */
export const readReports = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ReportsDto>(
      {url: `/reports`, method: 'GET', signal
    },
      options);
    }
  

export const getReadReportsQueryKey = () => {
    return [`/reports`] as const;
    }

    
export const getReadReportsQueryOptions = <TData = Awaited<ReturnType<typeof readReports>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReports>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReportsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReports>>> = ({ signal }) => readReports(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReportsQueryResult = NonNullable<Awaited<ReturnType<typeof readReports>>>
export type ReadReportsQueryError = unknown


export function useReadReports<TData = Awaited<ReturnType<typeof readReports>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReports>>,
          TError,
          Awaited<ReturnType<typeof readReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReports<TData = Awaited<ReturnType<typeof readReports>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReports>>,
          TError,
          Awaited<ReturnType<typeof readReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReports<TData = Awaited<ReturnType<typeof readReports>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReports>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Admin list of reports
 */

export function useReadReports<TData = Awaited<ReturnType<typeof readReports>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReports>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReportsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Resolve a report
 */
export const updateReport = (
    reportId: string,
    reportUpdateDto: ReportUpdateDto,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<ReportDto>(
      {url: `/reports/${reportId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: reportUpdateDto
    },
      options);
    }
  


export const getUpdateReportMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReport>>, TError,{reportId: string;data: ReportUpdateDto}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateReport>>, TError,{reportId: string;data: ReportUpdateDto}, TContext> => {

const mutationKey = ['updateReport'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReport>>, {reportId: string;data: ReportUpdateDto}> = (props) => {
          const {reportId,data} = props ?? {};

          return  updateReport(reportId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateReport>>>
    export type UpdateReportMutationBody = ReportUpdateDto
    export type UpdateReportMutationError = unknown

    /**
 * @summary Resolve a report
 */
export const useUpdateReport = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReport>>, TError,{reportId: string;data: ReportUpdateDto}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateReport>>,
        TError,
        {reportId: string;data: ReportUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdateReportMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    