/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { BenefitDtoType } from "./benefitDtoType";

export interface BenefitDto {
  /** Update timestamp */
  updatedAt: string;
  /** Unique identifier of the benefit */
  id: string;
  /** Market identifier this benefit belongs to */
  marketId: string;
  /** Type of benefit */
  type: BenefitDtoType;
  /** Name of the benefit */
  name: string;
  /** Detailed description of the benefit */
  description: string;
  /** Date when the benefit becomes valid */
  validFrom: string;
  /** Date when the benefit expires */
  validTo: string;
  /** URL of the benefit image */
  imageUrl?: string;

  status?: string;
}
