/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { BenefitsDto } from './benefitsDto';
import type { UserBenefitsDto } from './userBenefitsDto';

/**
 * Data containing benefits or user benefits
 */
export type BenefitsResponseDtoData = BenefitsDto | UserBenefitsDto;
