/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { BenefitDto } from './benefitDto';

export interface BenefitsDto {
  /** List of benefits returned in the current page */
  records: BenefitDto[];
  /** Number of records in this page */
  count: number;
  /** Total number of records across all pages */
  total: number;
  /**
   * Next offset for fetching the next page, null if no more records
   * @nullable
   */
  nextOffset?: number | null;
}
