/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { BenefitCreateDtoType } from './benefitCreateDtoType';

export interface BenefitCreateDto {
  /** Market identifier this benefit belongs to */
  marketId: string;
  /** Type of benefit */
  type: BenefitCreateDtoType;
  /** Name of the benefit */
  name: string;
  /** Detailed description of the benefit */
  description: string;
  /** Date when the benefit becomes valid */
  validFrom: string;
  /** Date when the benefit expires */
  validTo: string;
  /** URL of the benefit image */
  imageUrl?: string;
}
