/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { BenefitDto } from './benefitDto';

export interface BenefitConsumeResponseDto {
  /** Confirmation message */
  message: string;
  /** Date when the benefit was consumed */
  consumedAt: string;
  /** Details of the consumed benefit */
  benefit: BenefitDto;
}
