/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface BenefitClaimResponseDto {
  /** Validation code for the claimed benefit */
  code: string;
  /** Date when the benefit was claimed */
  claimedAt: string;
}
