/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export * from './benefitClaimResponseDto';
export * from './benefitConsumeResponseDto';
export * from './benefitCreateDto';
export * from './benefitCreateDtoType';
export * from './benefitDto';
export * from './benefitDtoType';
export * from './benefitUpdateDto';
export * from './benefitUpdateDtoType';
export * from './benefitsDto';
export * from './benefitsResponseDto';
export * from './benefitsResponseDtoData';
export * from './marketCreateDto';
export * from './marketDto';
export * from './marketUpdateDto';
export * from './marketsDto';
export * from './priceCreateDto';
export * from './priceDto';
export * from './pricesDto';
export * from './productCreateDto';
export * from './productDto';
export * from './productUpdateDto';
export * from './productsDto';
export * from './productsMergeDto';
export * from './readBenefitsParams';
export * from './readBenefitsType';
export * from './readMarketsParams';
export * from './readPricesParams';
export * from './readProductsParams';
export * from './reportCreateDto';
export * from './reportDto';
export * from './reportDtoStatus';
export * from './reportUpdateDto';
export * from './reportUpdateDtoStatus';
export * from './reportsDto';
export * from './uploadControllerUploadImageBody';
export * from './uploadImageDto';
export * from './userBenefitConsumeDto';
export * from './userBenefitDto';
export * from './userBenefitDtoStatus';
export * from './userBenefitsDto';