/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export type ReadBenefitsType = typeof ReadBenefitsType[keyof typeof ReadBenefitsType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReadBenefitsType = {
  VOUCHER: 'VOUCHER',
  GIFT: 'GIFT',
  DISCOUNT: 'DISCOUNT',
  CASHBACK: 'CASHBACK',
  FREEBIE: 'FREEBIE',
} as const;
