/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { ReadBenefitsType } from './readBenefitsType';

export type ReadBenefitsParams = {
/**
 * Offset for pagination
 */
offset?: number;
/**
 * Limit for pagination
 */
limit?: number;
/**
 * Field to order by
 */
orderBy?: string;
/**
 * Search term to filter benefits by name or description
 */
search?: string;
/**
 * Filter by benefit type
 */
type?: ReadBenefitsType;
/**
 * Filter by market ID
 */
marketId?: string;
/**
 * Only show active benefits (within valid date range)
 */
activeOnly?: boolean;
};
