/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { UserBenefitDtoStatus } from './userBenefitDtoStatus';
import type { BenefitDto } from './benefitDto';

export interface UserBenefitDto {
  /** Unique identifier of the user-benefit relationship */
  id: string;
  /** User identifier */
  userId: string;
  /** Benefit identifier */
  benefitId: string;
  /** Status of the user benefit */
  status: UserBenefitDtoStatus;
  /** Validation code for claiming/consuming the benefit */
  code?: string;
  /** Date when the benefit was assigned */
  assignedAt?: string;
  /** Date when the benefit was claimed */
  claimedAt?: string;
  /** Date when the benefit was consumed */
  consumedAt?: string;
  /** Benefit details */
  benefit?: BenefitDto;
}
