/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the user benefit
 */
export type UserBenefitDtoStatus = typeof UserBenefitDtoStatus[keyof typeof UserBenefitDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserBenefitDtoStatus = {
  ASSIGNED: 'ASSIGNED',
  CLAIMED: 'CLAIMED',
  CONSUMED: 'CONSUMED',
} as const;
