/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ProductCreateDto,
  ProductDto,
  ProductUpdateDto,
  ProductsDto,
  ReadProductsParams
} from '.././model';





/**
 * @summary Creates a new product.
 */
export const createProduct = (
    productCreateDto: ProductCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductDto>> => {
    
    
    return axios.post(
      `/products`,
      productCreateDto,options
    );
  }



export const getCreateProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: ProductCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: ProductCreateDto}, TContext> => {

const mutationKey = ['createProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduct>>, {data: ProductCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  createProduct(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>
    export type CreateProductMutationBody = ProductCreateDto
    export type CreateProductMutationError = AxiosError<unknown>

    /**
 * @summary Creates a new product.
 */
export const useCreateProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: ProductCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProduct>>,
        TError,
        {data: ProductCreateDto},
        TContext
      > => {

      const mutationOptions = getCreateProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Retrieves a list of products.
 */
export const readProducts = (
    params?: ReadProductsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductsDto>> => {
    
    
    return axios.get(
      `/products`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getReadProductsQueryKey = (params?: ReadProductsParams,) => {
    return [`/products`, ...(params ? [params]: [])] as const;
    }

    
export const getReadProductsQueryOptions = <TData = Awaited<ReturnType<typeof readProducts>>, TError = AxiosError<unknown>>(params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProducts>>> = ({ signal }) => readProducts(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProductsQueryResult = NonNullable<Awaited<ReturnType<typeof readProducts>>>
export type ReadProductsQueryError = AxiosError<unknown>


export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = AxiosError<unknown>>(
 params: undefined |  ReadProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProducts>>,
          TError,
          Awaited<ReturnType<typeof readProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = AxiosError<unknown>>(
 params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProducts>>,
          TError,
          Awaited<ReturnType<typeof readProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = AxiosError<unknown>>(
 params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a list of products.
 */

export function useReadProducts<TData = Awaited<ReturnType<typeof readProducts>>, TError = AxiosError<unknown>>(
 params?: ReadProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProductsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Retrieves a product by its ID.
 */
export const readProduct = (
    productId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductDto>> => {
    
    
    return axios.get(
      `/products/${productId}`,options
    );
  }


export const getReadProductQueryKey = (productId: string,) => {
    return [`/products/${productId}`] as const;
    }

    
export const getReadProductQueryOptions = <TData = Awaited<ReturnType<typeof readProduct>>, TError = AxiosError<unknown>>(productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadProductQueryKey(productId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readProduct>>> = ({ signal }) => readProduct(productId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(productId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadProductQueryResult = NonNullable<Awaited<ReturnType<typeof readProduct>>>
export type ReadProductQueryError = AxiosError<unknown>


export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = AxiosError<unknown>>(
 productId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProduct>>,
          TError,
          Awaited<ReturnType<typeof readProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = AxiosError<unknown>>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readProduct>>,
          TError,
          Awaited<ReturnType<typeof readProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = AxiosError<unknown>>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a product by its ID.
 */

export function useReadProduct<TData = Awaited<ReturnType<typeof readProduct>>, TError = AxiosError<unknown>>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadProductQueryOptions(productId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates a product by its ID.
 */
export const updateProduct = (
    productId: string,
    productUpdateDto: ProductUpdateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductDto>> => {
    
    
    return axios.patch(
      `/products/${productId}`,
      productUpdateDto,options
    );
  }



export const getUpdateProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{productId: string;data: ProductUpdateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{productId: string;data: ProductUpdateDto}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {productId: string;data: ProductUpdateDto}> = (props) => {
          const {productId,data} = props ?? {};

          return  updateProduct(productId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = ProductUpdateDto
    export type UpdateProductMutationError = AxiosError<unknown>

    /**
 * @summary Updates a product by its ID.
 */
export const useUpdateProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{productId: string;data: ProductUpdateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {productId: string;data: ProductUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdateProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Deletes a product by its ID.
 */
export const deleteProduct = (
    productId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/products/${productId}`,options
    );
  }



export const getDeleteProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  deleteProduct(productId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = AxiosError<unknown>

    /**
 * @summary Deletes a product by its ID.
 */
export const useDeleteProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {productId: string},
        TContext
      > => {

      const mutationOptions = getDeleteProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    