/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { ProductDto } from './productDto';
import type { MarketDto } from './marketDto';

export interface PriceDto {
  /** Product's image URL */
  imageUrl: string;
  /** User unique identifier */
  userId: string;
  /** Price's unique identifier */
  id: string;
  /** Product's price */
  price: number;
  /** Whether the price is currently moderated (approved for public view) */
  moderated: boolean;
  product: ProductDto;
  market: MarketDto;
}
