/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export type ReadPricesParams = {
/**
 * Product's unique identifier
 */
productId?: string;
/**
 * Market's unique identifier
 */
marketId?: string;
};
