/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */

export interface ReportDto {
  /** Report's unique identifier */
  reportId: string;
  /** Price's unique identifier */
  priceId: string;
  /** Report's reason */
  reason: string;
  /** Report's resolved status */
  resolved: boolean;
}
