/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import type { PriceDto } from './priceDto';
import type { ReportDtoStatus } from './reportDtoStatus';

export interface ReportDto {
  /** User unique identifier */
  userId: string;
  id: string;
  reason: string;
  resolved: boolean;
  price: PriceDto;
  status: ReportDtoStatus;
}
