/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SmartPreço API
 * SmartPreço API é uma API RESTful que fornece informações sobre mercados, produtos e seus preços.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  MarketsDto,
  ProductsDto
} from '.././model';





/**
 * @summary Get favorite products
 */
export const getFavoriteProducts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductsDto>> => {
    
    
    return axios.get(
      `/favorites/products`,options
    );
  }


export const getGetFavoriteProductsQueryKey = () => {
    return [`/favorites/products`] as const;
    }

    
export const getGetFavoriteProductsQueryOptions = <TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFavoriteProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavoriteProducts>>> = ({ signal }) => getFavoriteProducts({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFavoriteProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getFavoriteProducts>>>
export type GetFavoriteProductsQueryError = AxiosError<unknown>


export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteProducts>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteProducts>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get favorite products
 */

export function useGetFavoriteProducts<TData = Awaited<ReturnType<typeof getFavoriteProducts>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFavoriteProductsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Favorite a product
 */
export const favoriteProduct = (
    productId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/favorites/products/${productId}`,undefined,options
    );
  }



export const getFavoriteProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteProduct>>, TError,{productId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof favoriteProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['favoriteProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoriteProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  favoriteProduct(productId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FavoriteProductMutationResult = NonNullable<Awaited<ReturnType<typeof favoriteProduct>>>
    
    export type FavoriteProductMutationError = AxiosError<unknown>

    /**
 * @summary Favorite a product
 */
export const useFavoriteProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteProduct>>, TError,{productId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof favoriteProduct>>,
        TError,
        {productId: string},
        TContext
      > => {

      const mutationOptions = getFavoriteProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Unfavorite a product
 */
export const unfavoriteProduct = (
    productId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/favorites/products/${productId}`,options
    );
  }



export const getUnfavoriteProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteProduct>>, TError,{productId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unfavoriteProduct>>, TError,{productId: string}, TContext> => {

const mutationKey = ['unfavoriteProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfavoriteProduct>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  unfavoriteProduct(productId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfavoriteProductMutationResult = NonNullable<Awaited<ReturnType<typeof unfavoriteProduct>>>
    
    export type UnfavoriteProductMutationError = AxiosError<unknown>

    /**
 * @summary Unfavorite a product
 */
export const useUnfavoriteProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteProduct>>, TError,{productId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfavoriteProduct>>,
        TError,
        {productId: string},
        TContext
      > => {

      const mutationOptions = getUnfavoriteProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get favorite markets
 */
export const getFavoriteMarkets = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MarketsDto>> => {
    
    
    return axios.get(
      `/favorites/markets`,options
    );
  }


export const getGetFavoriteMarketsQueryKey = () => {
    return [`/favorites/markets`] as const;
    }

    
export const getGetFavoriteMarketsQueryOptions = <TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFavoriteMarketsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavoriteMarkets>>> = ({ signal }) => getFavoriteMarkets({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFavoriteMarketsQueryResult = NonNullable<Awaited<ReturnType<typeof getFavoriteMarkets>>>
export type GetFavoriteMarketsQueryError = AxiosError<unknown>


export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteMarkets>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteMarkets>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavoriteMarkets>>,
          TError,
          Awaited<ReturnType<typeof getFavoriteMarkets>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get favorite markets
 */

export function useGetFavoriteMarkets<TData = Awaited<ReturnType<typeof getFavoriteMarkets>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavoriteMarkets>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFavoriteMarketsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Favorite a market
 */
export const favoriteMarket = (
    marketId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/favorites/markets/${marketId}`,undefined,options
    );
  }



export const getFavoriteMarketMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteMarket>>, TError,{marketId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof favoriteMarket>>, TError,{marketId: string}, TContext> => {

const mutationKey = ['favoriteMarket'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoriteMarket>>, {marketId: string}> = (props) => {
          const {marketId} = props ?? {};

          return  favoriteMarket(marketId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FavoriteMarketMutationResult = NonNullable<Awaited<ReturnType<typeof favoriteMarket>>>
    
    export type FavoriteMarketMutationError = AxiosError<unknown>

    /**
 * @summary Favorite a market
 */
export const useFavoriteMarket = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof favoriteMarket>>, TError,{marketId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof favoriteMarket>>,
        TError,
        {marketId: string},
        TContext
      > => {

      const mutationOptions = getFavoriteMarketMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Unfavorite a market
 */
export const unfavoriteMarket = (
    marketId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/favorites/markets/${marketId}`,options
    );
  }



export const getUnfavoriteMarketMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteMarket>>, TError,{marketId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unfavoriteMarket>>, TError,{marketId: string}, TContext> => {

const mutationKey = ['unfavoriteMarket'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfavoriteMarket>>, {marketId: string}> = (props) => {
          const {marketId} = props ?? {};

          return  unfavoriteMarket(marketId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfavoriteMarketMutationResult = NonNullable<Awaited<ReturnType<typeof unfavoriteMarket>>>
    
    export type UnfavoriteMarketMutationError = AxiosError<unknown>

    /**
 * @summary Unfavorite a market
 */
export const useUnfavoriteMarket = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfavoriteMarket>>, TError,{marketId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfavoriteMarket>>,
        TError,
        {marketId: string},
        TContext
      > => {

      const mutationOptions = getUnfavoriteMarketMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    